### ISSUE TITLE
Newline within the /// comment has weird behaviour

### ISSUE THREAD

**Issue by rikkiprince** [alexermolov/CDocComments#4]
After typing `///` and generating a `/// <summary>` template, I find the behaviour for creating newlines within that comment a bit unusable.

For example, given a comment:
```
/// <summary>
/// first line
/// </summary>
```
pressing return after 'first line', will create a blank new line, such as:
```
/// <summary>
/// first line

/// </summary>
```
but then typing `///` inserts another newline, and then an additional `///` on the next line!
```
/// <summary>
/// first line
///
/// /// </summary>
```
I may just be using this wrong, but I've tried a few different orders of operations, and I've still not figured it out, which suggests it not massively intuitive.

My expected behaviour (particularly from using Visual Studio) would be that a newline after 'first line' would result in:
```
/// <summary>
/// first line
///
/// </summary>
```
Am I doing something wrong, or is this a bug?

**Comment by alexermolov** [comment]
Fixed in 1.0.5
